/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface OAuthConfig {
  'clientId' : string,
  'refreshToken' : string,
  'clientSecret' : string,
  'driveFolderId' : string,
}
export interface QueueItem {
  'fileName' : string,
  'orderIndex' : bigint,
  'driveFileId' : string,
}
export interface SchedulerState {
  'lastUploadDate' : string,
  'lastUploadTime' : bigint,
  'isEnabled' : boolean,
  'uploadsToday' : bigint,
}
export interface UploadHistoryEntry {
  'id' : bigint,
  'status' : string,
  'errorMessage' : string,
  'fileName' : string,
  'youtubeVideoId' : string,
  'uploadedAt' : bigint,
  'driveFileId' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToQueue' : ActorMethod<[QueueItem], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearQueue' : ActorMethod<[], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOAuthConfig' : ActorMethod<[], [] | [OAuthConfig]>,
  'getQueue' : ActorMethod<[], Array<QueueItem>>,
  'getSchedulerState' : ActorMethod<[], SchedulerState>,
  'getUploadHistory' : ActorMethod<[], Array<UploadHistoryEntry>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementUploadsToday' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordUpload' : ActorMethod<[UploadHistoryEntry], bigint>,
  'removeFromQueue' : ActorMethod<[string], undefined>,
  'reorderQueue' : ActorMethod<[Array<QueueItem>], undefined>,
  'resetDailyCount' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOAuthConfig' : ActorMethod<[OAuthConfig], undefined>,
  'setSchedulerEnabled' : ActorMethod<[boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];