/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QueueItem = IDL.Record({
  'fileName' : IDL.Text,
  'orderIndex' : IDL.Nat,
  'driveFileId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const OAuthConfig = IDL.Record({
  'clientId' : IDL.Text,
  'refreshToken' : IDL.Text,
  'clientSecret' : IDL.Text,
  'driveFolderId' : IDL.Text,
});
export const SchedulerState = IDL.Record({
  'lastUploadDate' : IDL.Text,
  'lastUploadTime' : IDL.Int,
  'isEnabled' : IDL.Bool,
  'uploadsToday' : IDL.Nat,
});
export const UploadHistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'errorMessage' : IDL.Text,
  'fileName' : IDL.Text,
  'youtubeVideoId' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'driveFileId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToQueue' : IDL.Func([QueueItem], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearQueue' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOAuthConfig' : IDL.Func([], [IDL.Opt(OAuthConfig)], ['query']),
  'getQueue' : IDL.Func([], [IDL.Vec(QueueItem)], ['query']),
  'getSchedulerState' : IDL.Func([], [SchedulerState], ['query']),
  'getUploadHistory' : IDL.Func([], [IDL.Vec(UploadHistoryEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementUploadsToday' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordUpload' : IDL.Func([UploadHistoryEntry], [IDL.Nat], []),
  'removeFromQueue' : IDL.Func([IDL.Text], [], []),
  'reorderQueue' : IDL.Func([IDL.Vec(QueueItem)], [], []),
  'resetDailyCount' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOAuthConfig' : IDL.Func([OAuthConfig], [], []),
  'setSchedulerEnabled' : IDL.Func([IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QueueItem = IDL.Record({
    'fileName' : IDL.Text,
    'orderIndex' : IDL.Nat,
    'driveFileId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const OAuthConfig = IDL.Record({
    'clientId' : IDL.Text,
    'refreshToken' : IDL.Text,
    'clientSecret' : IDL.Text,
    'driveFolderId' : IDL.Text,
  });
  const SchedulerState = IDL.Record({
    'lastUploadDate' : IDL.Text,
    'lastUploadTime' : IDL.Int,
    'isEnabled' : IDL.Bool,
    'uploadsToday' : IDL.Nat,
  });
  const UploadHistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'errorMessage' : IDL.Text,
    'fileName' : IDL.Text,
    'youtubeVideoId' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'driveFileId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToQueue' : IDL.Func([QueueItem], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearQueue' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOAuthConfig' : IDL.Func([], [IDL.Opt(OAuthConfig)], ['query']),
    'getQueue' : IDL.Func([], [IDL.Vec(QueueItem)], ['query']),
    'getSchedulerState' : IDL.Func([], [SchedulerState], ['query']),
    'getUploadHistory' : IDL.Func([], [IDL.Vec(UploadHistoryEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementUploadsToday' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordUpload' : IDL.Func([UploadHistoryEntry], [IDL.Nat], []),
    'removeFromQueue' : IDL.Func([IDL.Text], [], []),
    'reorderQueue' : IDL.Func([IDL.Vec(QueueItem)], [], []),
    'resetDailyCount' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOAuthConfig' : IDL.Func([OAuthConfig], [], []),
    'setSchedulerEnabled' : IDL.Func([IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };